### ISSUE TITLE
Gearbox setup-app broken with newer versions of pastedeploy

### ISSUE THREAD

**Issue by Amwam** [TurboGears/gearbox#30]
Following the example setup on on the TurboGears website, for wiki20.
https://turbogears.readthedocs.io/en/development/turbogears/wiki20.html#wiki20

I've tested this in a python 3.9.9 virtualenv
1. `pip install  tg.devtools`
1. `gearbox quickstart wiki20`
1. `pip install -e .`
2. Confirm that PasteDeploy==3.0.1 is installed by default (via `pip freeze`)
3. run `gearbox setup-app`

The following error appears (edited slightly to remove my computer paths)

```
21:17:52,209 ERROR [gearbox] 'PathDistribution' object has no attribute 'get_metadata_lines'
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.9/envs/tg-gearbox-pastedeploy-test/lib/python3.9/site-packages/gearbox/main.py", line 172, in _run_subcommand
    return cmd.run(parsed_args)
  File "~.pyenv/versions/3.9.9/envs/tg-gearbox-pastedeploy-test/lib/python3.9/site-packages/gearbox/command.py", line 31, in run
    self.take_action(parsed_args)
  File "~/.pyenv/versions/3.9.9/envs/tg-gearbox-pastedeploy-test/lib/python3.9/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "~/.pyenv/versions/3.9.9/envs/tg-gearbox-pastedeploy-test/lib/python3.9/site-packages/gearbox/commands/setup_app.py", line 70, in _setup_config
    modules = [line.strip() for line in dist.get_metadata_lines('top_level.txt')
AttributeError: 'PathDistribution' object has no attribute 'get_metadata_lines'
```

Installing `PasteDeploy==2.1.1`, will then allow `gearbox setup-app` to run. 
(Note this is also an issue with 3.0)

Apologies if this is actually an issue with PasteDeploy, I could not tell if this due to the use of the library, or the library itself. The release notes don't seem to mention this being removed.

**Comment by amol-** [comment]
should be fixed by https://github.com/TurboGears/gearbox/commit/26be1bd173d16b2d3022ff3628cf634f6a3aacbd
