### ISSUE TITLE
Error with sqlalchemy.url configuration with multiple databases

### ISSUE THREAD

**Issue by asarch** [TurboGears/gearbox#4]
With:

alembic==0.7.5.post2
Babel==1.3
backlash==0.0.7
Beaker==1.6.5.post1
cliff==1.10.1
cmd2==0.6.8
crank==0.7.2
decorator==3.4.2
FormEncode==1.3.0
gearbox==0.0.7
Genshi==0.7
Mako==1.0.1
MarkupSafe==0.23
PasteDeploy==1.5.2
pbr==0.10.8
prettytable==0.7.2
## FIXME: could not find svn URL in dependency_links for this package:
proyectos===0.1dev-r0
psycopg2==2.6
Pygments==2.0.2
pyparsing==2.0.3
pytz==2015.2
repoze.lru==0.6
repoze.who==2.2
six==1.9.0
speaklater==1.3
sprox==0.9.5
SQLAlchemy==0.9.9
stevedore==1.3.0
Tempita==0.5.2
tg.devtools==2.3.4
tgext.admin==0.6.4
tgext.crud==0.7.3
tgext.debugbar==0.2.4
transaction==1.4.3
TurboGears2==2.3.4
tw2.core==2.2.2
tw2.forms==2.2.2.1
WebOb==1.4
WebTest==1.4.3
zope.interface==4.1.2
zope.sqlalchemy==0.7.6

If you set as the manual says to enable multiple databases:

#sqlalchemy.url = sqlite:///%(here)s/devdata.db
sqlalchemy.first.url = sqlite:///%(here)s/devdata.db
sqlalchemy.second.url = sqlite:///%(here)s/devdata2.db

you get with "gearbox setup-app --debug":

23:51:05,660 WARNI [py.warnings] /home/asarch/tg2dev/lib/python2.7/site-packages/tw2/core/validation.py:12: ImportWarning: Not importing directory '/home/asarch/tg2dev/lib/python2.7/site-packages/tw2/core/i18n': missing __init__.py
  from .i18n import _

23:51:06,143 WARNI [py.warnings] /home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/dialects/__init__.py:35: SADeprecationWarning: The SQLAlchemy PostgreSQL dialect has been renamed from 'postgres' to 'postgresql'. The new URL format is postgresql[+driver]://<user>:<pass>@<host>/<dbname>
  module = __import__('sqlalchemy.dialects.%s' % (dialect, )).dialects

23:51:06,154 ERROR [gearbox] 'url'
Traceback (most recent call last):
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 303, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/command.py", line 53, in run
    self.take_action(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 93, in _setup_config
    self._call_setup_app(mod.setup_app, filename, section, vars)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 108, in _call_setup_app
    func(None, conf, vars)
  File "/home/asarch/tg2dev/proyectos/proyectos/websetup/__init__.py", line 17, in setup_app
    load_environment(conf.global_conf, conf.local_conf)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 794, in load_environment
    self.setup_persistence()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 590, in setup_persistence
    self.setup_sqlalchemy()
  File "/home/asarch/tg2dev/proyectos/proyectos/config/app_cfg.py", line 23, in setup_sqlalchemy
    engine = engine_from_config(config, 'sqlalchemy.')
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 407, in engine_from_config
    url = options.pop('url')
KeyError: 'url'
Running setup_app() from proyectos.websetup
Traceback (most recent call last):
  File "/home/asarch/tg2dev/bin/gearbox", line 9, in <module>
    load_entry_point('gearbox==0.0.7', 'console_scripts', 'gearbox')()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/main.py", line 94, in main
    return gearbox.run(args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 238, in run
    result = self.run_subcommand(remainder)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 303, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/command.py", line 53, in run
    self.take_action(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 93, in _setup_config
    self._call_setup_app(mod.setup_app, filename, section, vars)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 108, in _call_setup_app
    func(None, conf, vars)
  File "/home/asarch/tg2dev/proyectos/proyectos/websetup/__init__.py", line 17, in setup_app
    load_environment(conf.global_conf, conf.local_conf)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 794, in load_environment
    self.setup_persistence()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 590, in setup_persistence
    self.setup_sqlalchemy()
  File "/home/asarch/tg2dev/proyectos/proyectos/config/app_cfg.py", line 23, in setup_sqlalchemy
    engine = engine_from_config(config, 'sqlalchemy.')
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 407, in engine_from_config
    url = options.pop('url')
KeyError: 'url'

and if you just set the new url for the second database with:

sqlalchemy.url = sqlite:///%(here)s/devdata.db
sqlalchemy.second.url = sqlite:///%(here)s/devdata.db

you get with "gearbox setup-app --debug":

23:55:31,038 WARNI [py.warnings] /home/asarch/tg2dev/lib/python2.7/site-packages/tw2/core/validation.py:12: ImportWarning: Not importing directory '/home/asarch/tg2dev/lib/python2.7/site-packages/tw2/core/i18n': missing __init__.py
  from .i18n import _

23:55:31,511 ERROR [gearbox] Invalid argument(s) 'second.url' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
Traceback (most recent call last):
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 303, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/command.py", line 53, in run
    self.take_action(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 93, in _setup_config
    self._call_setup_app(mod.setup_app, filename, section, vars)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 108, in _call_setup_app
    func(None, conf, vars)
  File "/home/asarch/tg2dev/proyectos/proyectos/websetup/__init__.py", line 17, in setup_app
    load_environment(conf.global_conf, conf.local_conf)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 794, in load_environment
    self.setup_persistence()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 590, in setup_persistence
    self.setup_sqlalchemy()
  File "/home/asarch/tg2dev/proyectos/proyectos/config/app_cfg.py", line 23, in setup_sqlalchemy
    engine = engine_from_config(config, 'sqlalchemy.')
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 408, in engine_from_config
    return create_engine(url, **options)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 145, in create
    engineclass.__name__))
TypeError: Invalid argument(s) 'second.url' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
Running setup_app() from proyectos.websetup
Traceback (most recent call last):
  File "/home/asarch/tg2dev/bin/gearbox", line 9, in <module>
    load_entry_point('gearbox==0.0.7', 'console_scripts', 'gearbox')()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/main.py", line 94, in main
    return gearbox.run(args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 238, in run
    result = self.run_subcommand(remainder)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/app.py", line 303, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/cliff/command.py", line 53, in run
    self.take_action(parsed_args)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 53, in take_action
    self._setup_config(dist, config_file, section, {}, verbosity=self.app.options.verbose_level)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 93, in _setup_config
    self._call_setup_app(mod.setup_app, filename, section, vars)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/gearbox/commands/setup_app.py", line 108, in _call_setup_app
    func(None, conf, vars)
  File "/home/asarch/tg2dev/proyectos/proyectos/websetup/__init__.py", line 17, in setup_app
    load_environment(conf.global_conf, conf.local_conf)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 794, in load_environment
    self.setup_persistence()
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/tg/configuration/app_config.py", line 590, in setup_persistence
    self.setup_sqlalchemy()
  File "/home/asarch/tg2dev/proyectos/proyectos/config/app_cfg.py", line 23, in setup_sqlalchemy
    engine = engine_from_config(config, 'sqlalchemy.')
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 408, in engine_from_config
    return create_engine(url, **options)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/asarch/tg2dev/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 145, in create
    engineclass.__name__))
TypeError: Invalid argument(s) 'second.url' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by amol-** [comment]
Gearbox knows nothing about SQLAlchemy, the sqlalchemy setup process is performed by the webframework. In this case it looks like you are using TurboGears but you have a custom `setup_sqlalchemy` function in your `app_cfg.py`. 

Your implementation seems not to support multiple databases, you should remove the custom `setup_sqlalchemy` and rely on the default TG implementation or adapt your own function to support it.

**Comment by asarch** [comment]
What is then the correct way to add multiple databases support?

**Comment by asarch** [comment]
I really really sorry, this issue was for tg2docs. My mistake. Thank you very much.
