### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by 984958198** [TurboGears/gearbox#5]
'gearbox serve --daemon' will stuck when start it for a moment 
'gearbox serve --status' seems well,but get no response after a call

**Comment by amol-** [comment]
On which system is this happening? Which Python version?
Is this also happening on a newly quickstarted project?

I tested it on Python2.7 with OSX on a newly quickstarted project and everything seems to work as expected.

Can you try to change in your development.ini the logging configuration such as:
```
[handler_console]
class = FileHandler
args = ('/tmp/gearbox.log',)
level = NOTSET
formatter = generic
```

and then report the content of ``/tmp/gearbox.log`` ?

**Comment by 984958198** [comment]
[root@AY1407201415390290a8Z ~]# source tg2env/bin/activate
(tg2env)[root@AY1407201415390290a8Z ~]# uname -a
Linux AY1407201415390290a8Z 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
(tg2env)[root@AY1407201415390290a8Z ~]# head -n 1 /etc/issue
CentOS release 6.5 (Final)
(tg2env)[root@AY1407201415390290a8Z ~]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tg
>>> tg.version
'2.3.4'

I had opened the system-log.when I get some response ,I will call you.

**Comment by 984958198** [comment]
there is no error contained in log-file
but the program got stuck

**Comment by moschlar** [comment]
Maybe try starting gearbox like ``gearbox -v --debug [...]``

**Comment by moschlar** [comment]
I can actually confirm, that gearbox **fails silently** most of the time when something goes wrong with starting the server (e.g. socket bind or missing imports).
From a freshly quickstarted project with newest tg2 components from pypi:
```ShellSession
(blub)moschlar@thinkmo-lan /tmp/blub/demo $ gearbox serve
(blub)moschlar@thinkmo-lan /tmp/blub/demo $ gearbox -v serve
(blub)moschlar@thinkmo-lan /tmp/blub/demo $ gearbox -v --debug serve
15:51:02,603 WARNI [py.warnings] /tmp/blub/lib/python2.7/site-packages/pkg_resources/__init__.py:2263: DeprecationWarning: `require` parameter is deprecated. Use EntryPoint._load instead.
  DeprecationWarning,

Traceback (most recent call last):
  File "/tmp/blub/bin/gearbox", line 9, in <module>
    load_entry_point('gearbox==0.0.7', 'console_scripts', 'gearbox')()
  File "/tmp/blub/lib/python2.7/site-packages/gearbox/main.py", line 94, in main
    return gearbox.run(args)
  File "/tmp/blub/lib/python2.7/site-packages/cliff/app.py", line 241, in run
    result = self.run_subcommand(remainder)
  File "/tmp/blub/lib/python2.7/site-packages/cliff/app.py", line 314, in run_subcommand
    result = cmd.run(parsed_args)
  File "/tmp/blub/lib/python2.7/site-packages/cliff/command.py", line 54, in run
    self.take_action(parsed_args)
  File "/tmp/blub/lib/python2.7/site-packages/gearbox/commands/serve.py", line 282, in take_action
    serve()
  File "/tmp/blub/lib/python2.7/site-packages/gearbox/commands/serve.py", line 272, in serve
    server(app)
  File "/tmp/blub/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/tmp/blub/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/tmp/blub/lib/python2.7/site-packages/gearbox/commands/serve.py", line 842, in wsgiref_server_runner
    server = make_server(host, port, wsgi_app, server_class=GearboxWSGIServer)
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 151, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib64/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by amol-** [comment]
It was by design that it didn't provide full tracebacks of errors when ``--debug`` was not used, but that is actually confusing when the apps has not yet started because you get no error at all. In case of app errors you get only the error and you need ``--debug``  to get the whole traceback, but in case it failed before starting the app you actually get no errors and it just quits. 

I agree that it is a confusing behaviour that needs to be changed and errors need to be reported even when ``--debug`` is not used.

**Comment by amol-** [comment]
Tested on Python2.6 and it worked as expected.

Could you please provide ``pip freeze`` of your environment? Might it be that there is a package installed which doesn't work on Python2.6 and it's preventing gearbox from starting at all?

That would make possible for me to replicate the error with the same packages and versions

**Comment by 984958198** [comment]
(tg2env)[root@AY1407201415390290a8Z ~]# pip freeze
Babel==1.3
Beaker==1.7.0
FormEncode==1.3.0
Genshi==0.7
Mako==1.0.1
MarkupSafe==0.23
MySQL-python==1.2.5
PasteDeploy==1.5.2
SQLAlchemy==1.0.2
TGScheduler==1.7.0
Tempita==0.5.2
TurboGears2==2.3.2
WebOb==1.4.1
WebTest==1.4.3
alembic==0.7.5.post2
argparse==1.3.0
backlash==0.0.8
cliff==1.12.0
cmd2==0.6.8
crank==0.7.2
decorator==3.4.2
dqwebsvr==0.1dev
gearbox==0.0.7
pbr==0.10.8
prettytable==0.7.2
pyparsing==2.0.3
python-dateutil==1.5
pytz==2015.2
repoze.lru==0.6
repoze.who==2.2
six==1.9.0
speaklater==1.3
sprox==0.9.6
stevedore==1.4.0
tg.devtools==2.3.4
tgext.admin==0.6.4
tgext.asyncjob==0.3.1
tgext.crud==0.7.3
transaction==1.4.3
tw2.core==2.2.2
tw2.forms==2.2.2.1
xlrd==0.9.3
xlwt==1.0.0
zope.interface==4.1.2
zope.sqlalchemy==0.7.6
(tg2env)[root@AY1407201415390290a8Z ~]# 

I changed the version of TurboGears2 from 2.3.4 to 2.3.2 and start the TurboGears2 with the command 'gearbox -v --debug serve',
but stuck off after a day.
There is no abnormal information from console,the following error-logs come from 'gearbox.log'.Because of the error-logs arise in 'try',
so,i do not think that the error was caused by these errors.

2015-07-22 10:27:08,832 - sqlalchemy.engine.base.Engine - INFO - _rollback_impl - ROLLBACK
2015-07-22 10:27:08,832 - sqlalchemy.engine.base.Engine - INFO - _rollback_impl - ROLLBACK
2015-07-22 10:27:08,844 - dqwebsvr - WARNING - add_mentorship - (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '20105-4276602046863986511' for key 'unique_boxid_userid'") [SQL: u'INSERT INTO yst_user_prentice (create_time, update_time, boxid, userid, phone, time, master_id) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2015, 7, 22, 10, 27, 8, 830726), datetime.datetime(2015, 7, 22, 10, 27, 8, 830745), u'20105', '4276602046863986511', '15949569954', u'2015-07-22 10:18:44', 4L)]
2015-07-22 10:27:08,844 - dqwebsvr - WARNING - add_mentorship - (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '20105-4276602046863986511' for key 'unique_boxid_userid'") [SQL: u'INSERT INTO yst_user_prentice (create_time, update_time, boxid, userid, phone, time, master_id) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (datetime.datetime(2015, 7, 22, 10, 27, 8, 830726), datetime.datetime(2015, 7, 22, 10, 27, 8, 830745), u'20105', '4276602046863986511', '15949569954', u'2015-07-22 10:18:44', 4L)]
2015-07-22 10:27:08,848 - dqwebsvr - ERROR - add_movie_reserve - No JSON object could be decoded
Traceback (most recent call last):
  File "/mntubi/yst/code/dqwebsvr/dqwebsvr/controllers/yst_online/app.py", line 22, in add_movie_reserve
    reserve_list = json.loads(reserve_list)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2015-07-22 10:27:08,848 - dqwebsvr - ERROR - add_movie_reserve - No JSON object could be decoded
Traceback (most recent call last):
  File "/mntubi/yst/code/dqwebsvr/dqwebsvr/controllers/yst_online/app.py", line 22, in add_movie_reserve
    reserve_list = json.loads(reserve_list)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by 984958198** [comment]
When it stucked off,I use 'Ctrl+c',it get normal again and output the logs as follows.

14.28.139.112 - - [22/Jul/2015 09:52:33] "POST /ystonline/add_mentorship HTTP/1.1" 200 13
117.136.40.211 - - [22/Jul/2015 09:52:38] "POST /ystonline/add_movie_reserve HTTP/1.1" 200 45
117.136.40.211 - - [22/Jul/2015 09:52:42] "POST /ystonline/add_movie_reserve HTTP/1.1" 200 45






^C----------------------------------------
Exception happened during processing of request from ('117.136.40.211', 42683)
Traceback (most recent call last):
  File "/usr/lib64/python2.6/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 319, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 332, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.6/SocketServer.py", line 627, in __init__
    self.handle()
  File "/usr/lib64/python2.6/wsgiref/simple_server.py", line 130, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib64/python2.6/socket.py", line 450, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
14.28.139.112 - - [22/Jul/2015 10:25:30] "GET /recruit/add_recruit_clicks?userid=867739014070473&recruit_info_id=129 HTTP/1.1" 200 13
14.28.139.112 - - [22/Jul/2015 10:25:30] "GET /recruit/add_recruit_clicks?userid=867739014070473&recruit_info_id=129 HTTP/1.1" 200 13
14.28.139.112 - - [22/Jul/2015 10:25:30] "GET /tsv/task_message_num HTTP/1.1" 200 34

**Comment by amol-** [comment]
Are you serving with gearbox#wsgiref?
In such case I can see why you get stuck. Some browsers often leave their connection open, as wsgiref is single threaded by default they end up blocking the whole app. I have seen this behaviour often with IE.

You can check if that is the case by trying the ``wsgiref.threaded = true`` configuration option. If that solves your issue that was the cause.

In such case it's the expected behaviour as gearbox#wsgiref is a development only server and discouraged for production, so it just serves a single request at time.

**Comment by 984958198** [comment]
After i set 'wsgiref.threaded = true' ,I found too many 'ESTABLISHED' when i use 'netstat' to see the num total of connections.
It seems caused by my server .The client had left ,but the server did not close it and think it is still alive.
I used nginx to fix this problem,it looks like everything has gone better.

thank you
